#ifndef RLV_FEATURES_H
#define RLV_FEATURES_H

/**
 * Compile-time RichListview feature switches.
 * Defaults are conservative (off) unless the Makefile overrides them.
 */

#ifndef RLV_ENABLE_ALTERNATE_ROWS
#define RLV_ENABLE_ALTERNATE_ROWS  0
#endif

#ifndef RLV_ENABLE_ADAPTIVE_COLOURS
#define RLV_ENABLE_ADAPTIVE_COLOURS  0
#endif

#ifndef RLV_ENABLE_ADAPTIVE_ROW_PEN
#define RLV_ENABLE_ADAPTIVE_ROW_PEN  0
#endif

#ifndef RLV_ENABLE_ADAPTIVE_TITLE_PEN
#define RLV_ENABLE_ADAPTIVE_TITLE_PEN  0
#endif

#ifndef RLV_ENABLE_ADAPTIVE_SELECTION_PEN
#define RLV_ENABLE_ADAPTIVE_SELECTION_PEN  0
#endif

#ifndef RLV_ENABLE_ADAPTIVE_DIVIDERS
#define RLV_ENABLE_ADAPTIVE_DIVIDERS  0
#endif

#if defined(RLV_ENABLE_ADAPTIVE_ROW_PEN) && (RLV_ENABLE_ADAPTIVE_ROW_PEN != 0) \
    && (!defined(RLV_ENABLE_ALTERNATE_ROWS) || (RLV_ENABLE_ALTERNATE_ROWS == 0))
#error RLV_ENABLE_ADAPTIVE_ROW_PEN requires RLV_ENABLE_ALTERNATE_ROWS
#endif

#if defined(RLV_ENABLE_ADAPTIVE_ROW_PEN) && (RLV_ENABLE_ADAPTIVE_ROW_PEN != 0) \
    && (!defined(RLV_ENABLE_ADAPTIVE_COLOURS) || (RLV_ENABLE_ADAPTIVE_COLOURS == 0))
#error RLV_ENABLE_ADAPTIVE_ROW_PEN requires RLV_ENABLE_ADAPTIVE_COLOURS
#endif

#if defined(RLV_ENABLE_ADAPTIVE_TITLE_PEN) \
    && (RLV_ENABLE_ADAPTIVE_TITLE_PEN != 0) \
    && (!defined(RLV_ENABLE_ADAPTIVE_COLOURS) || (RLV_ENABLE_ADAPTIVE_COLOURS == 0))
#error RLV_ENABLE_ADAPTIVE_TITLE_PEN requires RLV_ENABLE_ADAPTIVE_COLOURS
#endif

#if defined(RLV_ENABLE_ADAPTIVE_SELECTION_PEN) \
    && (RLV_ENABLE_ADAPTIVE_SELECTION_PEN != 0) \
    && (!defined(RLV_ENABLE_ADAPTIVE_COLOURS) || (RLV_ENABLE_ADAPTIVE_COLOURS == 0))
#error RLV_ENABLE_ADAPTIVE_SELECTION_PEN requires RLV_ENABLE_ADAPTIVE_COLOURS
#endif

#if defined(RLV_ENABLE_ADAPTIVE_DIVIDERS) && (RLV_ENABLE_ADAPTIVE_DIVIDERS != 0) \
    && (!defined(RLV_ENABLE_ADAPTIVE_COLOURS) || (RLV_ENABLE_ADAPTIVE_COLOURS == 0))
#error RLV_ENABLE_ADAPTIVE_DIVIDERS requires RLV_ENABLE_ADAPTIVE_COLOURS
#endif

/* Shared engine needs ColorMap accessors on the V36 backend. */
#if defined(RLV_ENABLE_ADAPTIVE_COLOURS) && (RLV_ENABLE_ADAPTIVE_COLOURS != 0)
#define RLV_NEED_ADAPTIVE_COLORMAP  1
#else
#define RLV_NEED_ADAPTIVE_COLORMAP  0
#endif

#endif /* RLV_FEATURES_H */
